### ISSUE TITLE
download links don't work on status.julialang.org

### ISSUE THREAD

**Issue by Ken-B** [staticfloat/julia-nightly-packaging#2]
Not sure of this is the appropriate place to report it (happy to report it elsewhere..), but I'm looking for windows nightlies. 

The (Julia Ecosystem Status webpage)[http://status.julialang.org/] shows they have been built a few days ago, but the download links just self-reference. I also could not locate them on the amazon s3.

The relevent issue on JuliaLang:
https://github.com/JuliaLang/julia/issues/3812

Thanks a lot!

**Comment by staticfloat** [comment]
Expect news on this in the next couple days.  There is a large patch to the makefile build system I'm working on as I type this.  Once that lands, I will get these nightlies working properly.  I like to ensure that the build system is stable before publicizing the availability of these packages, and unfortunately as you can see the windows builds have gotten hung up by something again, so I'd like to fix those issues before I make the nightlies more widely available.

**Comment by staticfloat** [comment]
Closing this as all links now work.
