### ISSUE TITLE
Ubuntu nightlies failing

### ISSUE THREAD

**Issue by Keno** [staticfloat/julia-nightly-packaging#5]
Not sure if this is the right place to put it, but wherever I put it you'll see it anyway. It seems like the nightlies are failing because they're looking for `julia-basic` which was renamed to `julia`.

**Comment by staticfloat** [comment]
Hopefully addressed by https://github.com/staticfloat/julia-debian/commit/52bb7850e02c974e20b1f930d2fceb4b73fc02aa
