### ISSUE TITLE
Run test suite after build for logging purposes

### ISSUE THREAD

**Issue by tkelman** [staticfloat/julia-nightly-packaging#6]
Somewhat redundant with Travis for Linux build, but could be very informative on Mac and Windows. Can the cross-compile setup run the tests through Wine in a meaningful way?

**Comment by staticfloat** [comment]
Test suite is [already run for OSX](http://s3.amazonaws.com/julianightlies/logs/julia-0.3.0-prerelease-6de4d3b-osx10.7+.log), unfortunately we run into errors on Wine, so it always fails midway through the test suite.  I don't exactly remember what happens, @ihnorton do you know what happens when we `make testall` for windows cross-compile?

**Comment by tkelman** [comment]
Ah cool, missed that piece of the Mac log. Does the upload still happen if the tests fail on Mac?

**Comment by staticfloat** [comment]
No, it uploads a log but not the binary. This is all a part of my eventual
megalomaniacal plans to have the ultimate nightly build system, but alas
that's a lot of work, so for now we just have this. :P

**Comment by tkelman** [comment]
Just realized - if testing during the cross-compile is completely out of the question, we could leverage AppVeyor for this. I've temporarily given up on using AppVeyor for CI on the Julia repo because doing the build and running the tests together has been timing out for the last month and a half. But, if we only want to run the tests on the nightlies I think it could fit within 30 mins, and AppVeyor should have enough of an API to fire off a build every time a new Windows nightly gets uploaded, or just on a simple schedule. Thoughts?

**Comment by staticfloat** [comment]
I'm surprised that build/tests take longer than 30 minutes on AppVeyor.  Travis builds take ~15 minutes, give or take, and they run all the tests as well.  Are there packages (like LLVM or something similarly horrible) that are taking too long to build on AppVeyor?  Regardless, we should be able to install nightlies and run the tests in less than 30 minutes.  I would even guess that it should take less than 10 minutes, but we'll have to see. :)

I think this would be a neat thing to do, and I would be willing to help a bit, but I'm woefully out of touch with regards to the Windows side of things; I try to keep myself locked away in Linux/OSX land as much as possible, so I can definitely help with the "build notifications" and even display side of things, but actually dealing with AppVeyor is something that I think you're better equipped for than I.

**Comment by tkelman** [comment]
I only build a handful of dependencies in AppVeyor (just utf8proc and openlibm), the rest I download either from the latest Windows Julia binary, or from a Fedora cross-compile RPM, or from versions I built once and put on Sourceforge http://sourceforge.net/projects/juliadeps-win/files/

Downloading and compiling dependencies and everything up to the system image only takes about 5-6 minutes. Building the system image got way slower at the end of March (takes like 8-10 minutes now), and so did the time to run the tests. Some combination of AppVeyor switching to smaller VM's and changes in Julia codegen that made it slower. We only get one core to run the tests on, but multiple cores wouldn't help with the system image slowness. It's quite a bit faster on my local machine, even just on a single core.

**Comment by tkelman** [comment]
This does not bode well: https://ci.appveyor.com/project/tkelman/julia-nightly-packaging/build/job/6sqcdnwf7ve9gx3w

Why the heck is the test suite so ungodly slow in AppVeyor? Hover over the line numbers to see timestamps.

**Comment by staticfloat** [comment]
Wow.  That's quite impressive.

Julia automatically launches worker processes for every cpu core it can find, but if the machines these tests are being run on are only allocated a single core, this kind of slowdown would be expected.  Not necessarily the problem, but possibly one.  You might try forcing the number of workers to be only 1, instead of [however many CPU cores the machine advertises](https://github.com/JuliaLang/julia/blob/master/test/runtests.jl#L37).  Unfortunately, I've forgotten how to do this short of patching that particular line of `runtests.jl`.

**Comment by tkelman** [comment]
What's impressive about it? AppVeyor's pretty slick, I just wish it ran on beefier VM's.

If it was trying to run on more than 1 core, then we'd be seeing "From worker #:". It's a whole lot faster on my local machine, even when I `set JULIA_CPU_CORES=1`.

**Comment by staticfloat** [comment]
Oh, of course.  I'm out of ideas on how to speed this up then.  :/
