### ISSUE TITLE
Windows builds don't seem to be uploading their gitsha

### ISSUE THREAD

**Issue by staticfloat** [staticfloat/julia-nightly-packaging#7]
@ihnorton

Any idea why this might be happening?  Is your local build repository up to date?  The build scripts supposedly auto-update themselves, but I suppose if you're running on your own fork you wouldn't be getting my modifications.  :P

**Comment by ihnorton** [comment]
It's up to date now, and the SHA was just uploaded with the latest build.

**Comment by staticfloat** [comment]
Awesome, thanks!

**Comment by tkelman** [comment]
The redirects http://status.julialang.org/download/win64 are still pointing to yesterday's binary in http://s3.amazonaws.com/julialang rather than the new sha-labeled ones in http://s3.amazonaws.com/julianightlies, is the Windows script missing a post?

**Comment by staticfloat** [comment]
Fixed in db14819208f9a029f1fbeaac7220a2bb3927c2df, it will show up in the next build.
