### ISSUE TITLE
Ubuntu's package needs update

### ISSUE THREAD

**Issue by diegozea** [staticfloat/julia-nightly-packaging#9]
**ppa:staticfloat/julianightlies** needs an update in order to avoid the next issues:

https://github.com/JuliaStats/DataFrames.jl/issues/639
https://github.com/JuliaStats/StatsBase.jl/issues/79

Thanks!!! :)

**Comment by garborg** [comment]
And `DataFrames.jl` (and subsequently `ODBC.jl`) wants to use `Base.isidentifier`, et. al (JuliaLang/Julia#7540) to get colnames right when importing data.

**Comment by garborg** [comment]
Looks like they're up-to-date now -- thanks!

**Comment by staticfloat** [comment]
Yes, sorry!  We had a bit of a hangup and I just now was able to address it.  As a bonus, the nightlies are now on `0.3.0-rc1`.

**Comment by garborg** [comment]
Yes, exciting!

**Comment by diegozea** [comment]
Great :)
